# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57b94e91b06d224021564ea6756e8251"
name = "wishlist-01"
handle = "wishlist-01"
application_url = "https://wishlist-01-5822be6dd7e8.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "cofaria-01.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://wishlist-01-5822be6dd7e8.herokuapp.com/auth/callback",
  "https://wishlist-01-5822be6dd7e8.herokuapp.com/auth/shopify/callback",
  "https://wishlist-01-5822be6dd7e8.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
